# Generated by Django 6.0.2 on 2026-02-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=70, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/products/')),
                ('manufactured_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
