# Generated by Django 6.0 on 2026-04-06 07:36

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_product_id_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Distribution center ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')])),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=255)),
                ('service_region', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'distribution_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Inventory ID')),
                ('quantity_on_hand', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='On-hand quantity cannot be negative')])),
                ('reorder_point', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Reorder point cannot be negative')])),
                ('max_stock_level', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['warehouse_id', 'product_id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Purchase order ID')),
                ('order_number', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')])),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Unit price must be zero or greater')])),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'purchase_order_items',
                'ordering': ['purchase_order_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Shipment ID')),
                ('shipment_number', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')])),
                ('ship_date', models.DateField()),
                ('expected_arrival_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('carrier', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-ship_date', 'shipment_number'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'shipment_items',
                'ordering': ['shipment_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Warehouse ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')])),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=255)),
                ('capacity_sqft', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='Capacity must be greater than zero')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2026, 4, 6)),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.date(2026, 4, 6)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'], message='Only JPG, PNG and GIF images are allowed')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=70, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Unit price must be zero or greater')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, digits, and internal hyphens are allowed.', regex='^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Tunisian phone number must start with +216 and be 8 digits long', regex='^\\+216\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0, message='Rating must be positive or zero'), django.core.validators.MaxValueValidator(5.0, message='Rating must be less than or equal to 5.0')]),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='suppliers_is_acti_a163b0_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['rating'], name='suppliers_rating_965dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='product_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='supplier_rating_between_0_5'),
        ),
        migrations.AddIndex(
            model_name='distributioncenter',
            index=models.Index(fields=['code'], name='distributio_code_f6d991_idx'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_records', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='product_app.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_order_items', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_app.purchaseorder'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distribution_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='product_app.distributioncenter'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipment_items', to='product_app.product'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product_app.shipment'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='warehouses_code_339055_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active'], name='warehouses_is_acti_178fdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.CheckConstraint(condition=models.Q(('capacity_sqft__gt', 0)), name='warehouse_capacity_positive'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipments', to='product_app.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='product_app.warehouse'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='purchase_or_order_n_51aa62_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchase_or_order_d_409199_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status', 'order_date'], name='purchase_or_supplie_278cc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('expected_delivery_date__gt', models.F('order_date'))), name='purchase_order_delivery_after_order_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='purchase_order_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['quantity'], name='purchase_or_quantit_5a71d5_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderitem',
            index=models.Index(fields=['purchase_order', 'product'], name='purchase_or_purchas_08ed91_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'product'), name='unique_product_per_purchase_order'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='po_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='po_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='po_item_subtotal_non_negative'),
        ),
        migrations.AddIndex(
            model_name='shipmentitem',
            index=models.Index(fields=['shipment', 'product'], name='shipment_it_shipmen_d746ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'product'), name='unique_product_per_shipment'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shipment_item_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['shipment_number'], name='shipments_shipmen_67925e_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_status_cda325_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['ship_date'], name='shipments_ship_da_e29271_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['warehouse', 'status', 'ship_date'], name='shipments_warehou_223499_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('expected_arrival_date__gt', models.F('ship_date'))), name='shipment_arrival_after_ship_date'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['warehouse', 'product', 'quantity_on_hand'], name='inventory_warehou_101b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['product', 'quantity_on_hand'], name='inventory_product_507966_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['last_updated'], name='inventory_last_up_f611e9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['quantity_on_hand'], name='inventory_quantit_c50ee4_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_inventory_per_warehouse_product'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_on_hand__gte', 0)), name='inventory_qty_on_hand_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__gte', 0)), name='inventory_reorder_point_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('max_stock_level__gt', 0)), name='inventory_max_stock_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__lt', models.F('max_stock_level'))), name='inventory_reorder_below_max'),
        ),
    ]
