# Generated by Django 6.0 on 2026-04-19 18:48

import product_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_relocate_models_to_domain_apps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=product_app.models._today),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=product_app.models._today),
        ),
    ]
