# Generated by Django 6.0 on 2026-04-06 07:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_app", "0007_relocate_models_to_domain_apps"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Warehouse",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Warehouse ID",
                            ),
                        ),
                        (
                            "code",
                            models.CharField(
                                max_length=50,
                                unique=True,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Only letters, digits, and internal hyphens are allowed.",
                                        regex="^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$",
                                    )
                                ],
                            ),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("location", models.CharField(max_length=255)),
                        (
                            "capacity_sqft",
                            models.DecimalField(
                                decimal_places=2,
                                max_digits=12,
                                validators=[
                                    django.core.validators.MinValueValidator(
                                        0.01,
                                        message="Capacity must be greater than zero",
                                    )
                                ],
                            ),
                        ),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "db_table": "warehouses",
                        "ordering": ["code"],
                        "indexes": [
                            models.Index(
                                fields=["code"], name="warehouses_code_339055_idx"
                            ),
                            models.Index(
                                fields=["is_active"],
                                name="warehouses_is_acti_178fdd_idx",
                            ),
                        ],
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(("capacity_sqft__gt", 0)),
                                name="warehouse_capacity_positive",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="Inventory",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Inventory ID",
                            ),
                        ),
                        (
                            "quantity_on_hand",
                            models.IntegerField(
                                default=0,
                                validators=[
                                    django.core.validators.MinValueValidator(
                                        0,
                                        message="On-hand quantity cannot be negative",
                                    )
                                ],
                            ),
                        ),
                        (
                            "reorder_point",
                            models.IntegerField(
                                validators=[
                                    django.core.validators.MinValueValidator(
                                        0,
                                        message="Reorder point cannot be negative",
                                    )
                                ],
                            ),
                        ),
                        ("max_stock_level", models.IntegerField()),
                        ("last_updated", models.DateTimeField(auto_now=True)),
                        (
                            "product",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="inventory_records",
                                to="product_app.product",
                            ),
                        ),
                        (
                            "warehouse",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="inventory_records",
                                to="warehouse_app.warehouse",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "inventory",
                        "ordering": ["warehouse_id", "product_id"],
                        "indexes": [
                            models.Index(
                                fields=["warehouse", "product", "quantity_on_hand"],
                                name="inventory_warehou_101b4e_idx",
                            ),
                            models.Index(
                                fields=["product", "quantity_on_hand"],
                                name="inventory_product_507966_idx",
                            ),
                            models.Index(
                                fields=["last_updated"],
                                name="inventory_last_up_f611e9_idx",
                            ),
                            models.Index(
                                fields=["quantity_on_hand"],
                                name="inventory_quantit_c50ee4_idx",
                            ),
                        ],
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("warehouse", "product"),
                                name="unique_inventory_per_warehouse_product",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("quantity_on_hand__gte", 0)),
                                name="inventory_qty_on_hand_non_negative",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("reorder_point__gte", 0)),
                                name="inventory_reorder_point_non_negative",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(("max_stock_level__gt", 0)),
                                name="inventory_max_stock_positive",
                            ),
                            models.CheckConstraint(
                                condition=models.Q(
                                    ("reorder_point__lt", models.F("max_stock_level"))
                                ),
                                name="inventory_reorder_below_max",
                            ),
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
