# Generated by Django 6.0 on 2026-04-06 07:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_app", "0007_relocate_models_to_domain_apps"),
        ("warehouse_app", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ShipmentItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("quantity", models.PositiveIntegerField()),
                    ],
                    options={
                        "db_table": "shipment_items",
                        "ordering": ["shipment_id", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="DistributionCenter",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Distribution center ID",
                            ),
                        ),
                        (
                            "code",
                            models.CharField(
                                max_length=50,
                                unique=True,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Only letters, digits, and internal hyphens are allowed.",
                                        regex="^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$",
                                    )
                                ],
                            ),
                        ),
                        ("name", models.CharField(max_length=120)),
                        ("location", models.CharField(max_length=255)),
                        ("service_region", models.CharField(max_length=120)),
                        ("is_active", models.BooleanField(default=True)),
                    ],
                    options={
                        "db_table": "distribution_centers",
                        "ordering": ["code"],
                        "indexes": [
                            models.Index(
                                fields=["code"], name="distributio_code_f6d991_idx"
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="Shipment",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Shipment ID",
                            ),
                        ),
                        (
                            "shipment_number",
                            models.CharField(
                                max_length=64,
                                unique=True,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Only letters, digits, and internal hyphens are allowed.",
                                        regex="^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$",
                                    )
                                ],
                            ),
                        ),
                        ("ship_date", models.DateField()),
                        ("expected_arrival_date", models.DateField()),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("PENDING", "Pending"),
                                    ("IN_TRANSIT", "In transit"),
                                    ("DELIVERED", "Delivered"),
                                    ("DELAYED", "Delayed"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                default="PENDING",
                                max_length=20,
                            ),
                        ),
                        ("carrier", models.CharField(max_length=120)),
                        (
                            "distribution_center",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.RESTRICT,
                                related_name="shipments",
                                to="distribution_app.distributioncenter",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "shipments",
                        "ordering": ["-ship_date", "shipment_number"],
                    },
                ),
                migrations.AddField(
                    model_name="shipment",
                    name="warehouse",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shipments",
                        to="warehouse_app.warehouse",
                    ),
                ),
                migrations.AddField(
                    model_name="shipmentitem",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="shipment_items",
                        to="product_app.product",
                    ),
                ),
                migrations.AddField(
                    model_name="shipmentitem",
                    name="shipment",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="distribution_app.shipment",
                    ),
                ),
                migrations.AddIndex(
                    model_name="shipment",
                    index=models.Index(
                        fields=["shipment_number"],
                        name="shipments_shipmen_67925e_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="shipment",
                    index=models.Index(
                        fields=["status"], name="shipments_status_cda325_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="shipment",
                    index=models.Index(
                        fields=["ship_date"], name="shipments_ship_da_e29271_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="shipment",
                    index=models.Index(
                        fields=["warehouse", "status", "ship_date"],
                        name="shipments_warehou_223499_idx",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="shipment",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("expected_arrival_date__gt", models.F("ship_date"))
                        ),
                        name="shipment_arrival_after_ship_date",
                    ),
                ),
                migrations.AddIndex(
                    model_name="shipmentitem",
                    index=models.Index(
                        fields=["shipment", "product"],
                        name="shipment_it_shipmen_d746ec_idx",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="shipmentitem",
                    constraint=models.UniqueConstraint(
                        fields=("shipment", "product"),
                        name="unique_product_per_shipment",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="shipmentitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="shipment_item_qty_positive",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
