# Generated by Django 6.0 on 2026-04-06 07:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_app", "0007_relocate_models_to_domain_apps"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Supplier",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Supplier ID",
                            ),
                        ),
                        ("name", models.CharField(max_length=50)),
                        (
                            "code",
                            models.CharField(
                                max_length=50,
                                unique=True,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Only letters, digits, and internal hyphens are allowed.",
                                        regex="^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$",
                                    )
                                ],
                            ),
                        ),
                        ("email", models.EmailField(max_length=254, unique=True)),
                        (
                            "phone",
                            models.CharField(
                                max_length=20,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Tunisian phone number must start with +216 and be 8 digits long",
                                        regex=r"^\+216\d{8}$",
                                    )
                                ],
                            ),
                        ),
                        ("address", models.TextField()),
                        ("is_active", models.BooleanField(default=True)),
                        (
                            "rating",
                            models.DecimalField(
                                decimal_places=1,
                                default=0.0,
                                max_digits=2,
                                validators=[
                                    django.core.validators.MinValueValidator(
                                        0.0,
                                        message="Rating must be positive or zero",
                                    ),
                                    django.core.validators.MaxValueValidator(
                                        5.0,
                                        message="Rating must be less than or equal to 5.0",
                                    ),
                                ],
                            ),
                        ),
                    ],
                    options={
                        "db_table": "suppliers",
                        "ordering": ["name"],
                    },
                ),
                migrations.CreateModel(
                    name="SupplierProduct",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "product",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="product_app.product",
                            ),
                        ),
                        (
                            "supplier",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="supplier_app.supplier",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "suppliers_products",
                    },
                ),
                migrations.AddField(
                    model_name="supplier",
                    name="products",
                    field=models.ManyToManyField(
                        related_name="supplier_products",
                        through="supplier_app.SupplierProduct",
                        to="product_app.product",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="supplierproduct",
                    constraint=models.UniqueConstraint(
                        fields=("supplier", "product"),
                        name="suppliers_products_supplier_id_product_id_a79c6028_uniq",
                    ),
                ),
                migrations.AddIndex(
                    model_name="supplier",
                    index=models.Index(
                        fields=["name", "code"], name="suppliers_name_a0c024_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="supplier",
                    index=models.Index(
                        fields=["is_active"], name="suppliers_is_acti_a163b0_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="supplier",
                    index=models.Index(
                        fields=["rating"], name="suppliers_rating_965dcb_idx"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="supplier",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("rating__gte", 0), ("rating__lte", 5)
                        ),
                        name="supplier_rating_between_0_5",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
