# Generated by Django 6.0 on 2026-04-06 07:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product_app", "0007_relocate_models_to_domain_apps"),
        ("supplier_app", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PurchaseOrder",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                                verbose_name="Purchase order ID",
                            ),
                        ),
                        (
                            "order_number",
                            models.CharField(
                                max_length=64,
                                unique=True,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="Only letters, digits, and internal hyphens are allowed.",
                                        regex="^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$",
                                    )
                                ],
                            ),
                        ),
                        ("order_date", models.DateField()),
                        ("expected_delivery_date", models.DateField()),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("DRAFT", "Draft"),
                                    ("SUBMITTED", "Submitted"),
                                    ("CONFIRMED", "Confirmed"),
                                    ("IN_TRANSIT", "In transit"),
                                    ("RECEIVED", "Received"),
                                    ("CANCELLED", "Cancelled"),
                                ],
                                default="DRAFT",
                                max_length=20,
                            ),
                        ),
                        (
                            "total_amount",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=14
                            ),
                        ),
                    ],
                    options={
                        "db_table": "purchase_orders",
                        "ordering": ["-order_date", "order_number"],
                    },
                ),
                migrations.CreateModel(
                    name="PurchaseOrderItem",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("quantity", models.PositiveIntegerField()),
                        (
                            "unit_price",
                            models.DecimalField(
                                decimal_places=2,
                                max_digits=10,
                                validators=[
                                    django.core.validators.MinValueValidator(
                                        0,
                                        message="Unit price must be zero or greater",
                                    )
                                ],
                            ),
                        ),
                        (
                            "subtotal",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=14
                            ),
                        ),
                    ],
                    options={
                        "db_table": "purchase_order_items",
                        "ordering": ["purchase_order_id", "id"],
                    },
                ),
                migrations.AddField(
                    model_name="purchaseorder",
                    name="supplier",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_orders",
                        to="supplier_app.supplier",
                    ),
                ),
                migrations.AddField(
                    model_name="purchaseorderitem",
                    name="product",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="purchase_order_items",
                        to="product_app.product",
                    ),
                ),
                migrations.AddField(
                    model_name="purchaseorderitem",
                    name="purchase_order",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order_app.purchaseorder",
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["order_number"], name="purchase_or_order_n_51aa62_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["status"], name="purchase_or_status_5ac239_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["order_date"], name="purchase_or_order_d_409199_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorder",
                    index=models.Index(
                        fields=["supplier", "status", "order_date"],
                        name="purchase_or_supplie_278cc1_idx",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorder",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("expected_delivery_date__gt", models.F("order_date"))
                        ),
                        name="purchase_order_delivery_after_order_date",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorder",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("total_amount__gte", 0)),
                        name="purchase_order_total_non_negative",
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorderitem",
                    index=models.Index(
                        fields=["quantity"], name="purchase_or_quantit_5a71d5_idx"
                    ),
                ),
                migrations.AddIndex(
                    model_name="purchaseorderitem",
                    index=models.Index(
                        fields=["purchase_order", "product"],
                        name="purchase_or_purchas_08ed91_idx",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorderitem",
                    constraint=models.UniqueConstraint(
                        fields=("purchase_order", "product"),
                        name="unique_product_per_purchase_order",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorderitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="po_item_qty_positive",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorderitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("unit_price__gte", 0)),
                        name="po_item_unit_price_non_negative",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="purchaseorderitem",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("subtotal__gte", 0)),
                        name="po_item_subtotal_non_negative",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
